//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalColor
    {
        public int id_choosenColor { get; set; }
        public byte choosenColorRed { get; set; }
        public byte choosenColorGreen { get; set; }
        public byte choosenColorBlue { get; set; }
    }
}
