//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewColor
    {
        public int id_kolor { get; set; }
        public int rgb_red { get; set; }
        public int rgb_green { get; set; }
        public int rgb_blue { get; set; }
    }
}
