//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewProject
    {
        public int ID_project { get; set; }
        public string projectName { get; set; }
        public Nullable<int> boardSize { get; set; }
        public Nullable<int> squareSize { get; set; }
        public string defaultSquareFill { get; set; }
        public Nullable<bool> description { get; set; }
    }
}
