//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class SquareFill
    {
        public int id_project { get; set; }
        public int id_defaultSquareFill { get; set; }
        public byte defaultRed { get; set; }
        public byte defaultGreen { get; set; }
        public byte defaultBlue { get; set; }
    
        public virtual NewProject NewProject { get; set; }
    }
}
